# Generated by Django 2.2.7 on 2019-12-05 11:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OSINT_System_Core', '0002_auto_20191205_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Target_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ess_target_reff', models.CharField(max_length=100, null=True)),
                ('author_type', models.CharField(choices=[('facebook_person', 'Author is a Facebook Users Profile'), ('facebook_page', 'Author is a Facebook Page'), ('facebook_group', 'Author is a Facebook Group'), ('facebook_hashtag', 'Author is a Facebook HashTag'), ('facebook_search', 'Author is a Facebook Search'), ('twitter_person', 'Author is a Twitter Person'), ('twitter_search', 'Author is a Twitter Search'), ('instagram_author', 'Author is a Instagram Person'), ('instagram_search', 'Author is a Instagram Search')], max_length=100)),
                ('social_site_reff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OSINT_System_Core.Supported_Socail_Sites')),
            ],
        ),
        migrations.CreateModel(
            name='Twitter_Target_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=100)),
                ('author_account', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('author_url', models.URLField()),
                ('expired_on', models.DurationField()),
                ('is_enabled', models.BooleanField(choices=[(True, 'Target is Enabled'), (False, 'Target is Disabled')], default=True)),
                ('is_expired', models.BooleanField(choices=[(True, 'Target is Expired'), (False, 'Target is Functional')], default=False)),
                ('need_screenshots', models.BooleanField(default=False)),
                ('periodic_interval', models.IntegerField(choices=[(5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 11, 32, 46, 449732, tzinfo=utc))),
                ('global_target_reff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Public_Data_Acquisition_Unit.Global_Target_Record')),
            ],
        ),
        migrations.CreateModel(
            name='Twitter_Target_Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_keywords', models.CharField(max_length=1000)),
                ('web_page_url', models.URLField()),
                ('expired_on', models.DurationField()),
                ('is_enabled', models.BooleanField(choices=[(True, 'Target is Enabled'), (False, 'Target is Disabled')], default=True)),
                ('is_expired', models.BooleanField(choices=[(True, 'Target is Expired'), (False, 'Target is Functional')], default=False)),
                ('periodic_interval', models.IntegerField(choices=[(5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 11, 32, 46, 450155, tzinfo=utc))),
                ('global_target_reff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Public_Data_Acquisition_Unit.Global_Target_Record')),
            ],
        ),
        migrations.CreateModel(
            name='Facebook_Target_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_keywords', models.CharField(max_length=1000)),
                ('web_page_url', models.URLField()),
                ('expired_on', models.DurationField()),
                ('is_enabled', models.BooleanField(choices=[(True, 'Target is Enabled'), (False, 'Target is Disabled')], default=True)),
                ('is_expired', models.BooleanField(choices=[(True, 'Target is Expired'), (False, 'Target is Functional')], default=False)),
                ('periodic_interval', models.IntegerField(choices=[(5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 11, 32, 46, 449296, tzinfo=utc))),
                ('global_target_reff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Public_Data_Acquisition_Unit.Global_Target_Record')),
            ],
        ),
        migrations.CreateModel(
            name='Facebook_Target_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=100)),
                ('author_account', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('author_url', models.URLField()),
                ('expired_on', models.DurationField()),
                ('is_enabled', models.BooleanField(choices=[(True, 'Target is Enabled'), (False, 'Target is Disabled')], default=True)),
                ('is_expired', models.BooleanField(choices=[(True, 'Target is Expired'), (False, 'Target is Functional')], default=False)),
                ('need_screenshots', models.BooleanField(default=False)),
                ('periodic_interval', models.IntegerField(choices=[(5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 11, 32, 46, 447107, tzinfo=utc))),
                ('global_target_reff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Public_Data_Acquisition_Unit.Global_Target_Record')),
            ],
        ),
        migrations.CreateModel(
            name='Facebook_Target_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=100)),
                ('page_account', models.CharField(max_length=100)),
                ('page_name', models.CharField(max_length=100)),
                ('page_url', models.URLField()),
                ('expired_on', models.DurationField()),
                ('is_enabled', models.BooleanField(choices=[(True, 'Target is Enabled'), (False, 'Target is Disabled')], default=True)),
                ('is_expired', models.BooleanField(choices=[(True, 'Target is Expired'), (False, 'Target is Functional')], default=False)),
                ('need_screenshots', models.BooleanField(default=False)),
                ('periodic_interval', models.IntegerField(choices=[(5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 11, 32, 46, 447562, tzinfo=utc))),
                ('global_target_reff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Public_Data_Acquisition_Unit.Global_Target_Record')),
            ],
        ),
        migrations.CreateModel(
            name='Facebook_Target_Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_keywords', models.CharField(max_length=1000)),
                ('web_page_url', models.URLField()),
                ('expired_on', models.DurationField()),
                ('is_enabled', models.BooleanField(choices=[(True, 'Target is Enabled'), (False, 'Target is Disabled')], default=True)),
                ('is_expired', models.BooleanField(choices=[(True, 'Target is Expired'), (False, 'Target is Functional')], default=False)),
                ('periodic_interval', models.IntegerField(choices=[(5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 11, 32, 46, 448868, tzinfo=utc))),
                ('global_target_reff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Public_Data_Acquisition_Unit.Global_Target_Record')),
            ],
        ),
        migrations.CreateModel(
            name='Facebook_Target_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100)),
                ('group_url', models.URLField()),
                ('expired_on', models.DurationField()),
                ('is_enabled', models.BooleanField(choices=[(True, 'Target is Enabled'), (False, 'Target is Disabled')], default=True)),
                ('is_expired', models.BooleanField(choices=[(True, 'Target is Expired'), (False, 'Target is Functional')], default=False)),
                ('need_screenshots', models.BooleanField(default=False)),
                ('periodic_interval', models.IntegerField(choices=[(5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 11, 32, 46, 448446, tzinfo=utc))),
                ('global_target_reff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Public_Data_Acquisition_Unit.Global_Target_Record')),
            ],
        ),
    ]
