# Generated by Django 2.2.7 on 2019-12-30 09:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Public_Data_Acquisition_Unit', '0007_auto_20191217_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook_target_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 9, 14, 55, 23821, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facebook_target_hashtag',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 9, 14, 55, 24266, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facebook_target_page',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 9, 14, 55, 23360, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facebook_target_person',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 9, 14, 55, 22782, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facebook_target_search',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 9, 14, 55, 24686, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instagram_target_person',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 9, 14, 55, 26968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instagram_target_search',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 9, 14, 55, 27656, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news_site_target',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 9, 14, 55, 26526, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='twitter_target_hashtag',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 9, 14, 55, 25630, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='twitter_target_person',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 9, 14, 55, 25191, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Twitter_Target_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtags', models.CharField(default='', max_length=200)),
                ('phrase', models.CharField(default='', max_length=200)),
                ('date', models.CharField(default='', max_length=30)),
                ('distance', models.CharField(default='', max_length=20)),
                ('search_type', models.CharField(choices=[('phrase', 'search using hashtags'), ('hashtag', 'search using hashtags'), ('location', 'search using hashtags'), ('bydate', 'search using hashtags')], max_length=50)),
                ('expired_on', models.DurationField()),
                ('is_enabled', models.BooleanField(choices=[(True, 'Target is Enabled'), (False, 'Target is Disabled')], default=True)),
                ('is_expired', models.BooleanField(choices=[(True, 'Target is Expired'), (False, 'Target is Functional')], default=False)),
                ('periodic_interval', models.IntegerField(choices=[(5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2019, 12, 30, 9, 14, 55, 26093, tzinfo=utc))),
                ('global_target_reff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Public_Data_Acquisition_Unit.Global_Target_Record')),
            ],
        ),
    ]
