# Generated by Django 2.2.7 on 2020-01-01 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Public_Data_Acquisition_Unit', '0010_auto_20191230_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook_target_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 9, 45, 22, 104026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facebook_target_group',
            name='periodic_interval',
            field=models.IntegerField(choices=[(0, 'on time only'), (5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='facebook_target_hashtag',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 9, 45, 22, 104468, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facebook_target_hashtag',
            name='periodic_interval',
            field=models.IntegerField(choices=[(0, 'on time only'), (5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='facebook_target_page',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 9, 45, 22, 103555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facebook_target_page',
            name='periodic_interval',
            field=models.IntegerField(choices=[(0, 'on time only'), (5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='facebook_target_person',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 9, 45, 22, 102942, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facebook_target_person',
            name='expired_on',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='facebook_target_person',
            name='periodic_interval',
            field=models.IntegerField(choices=[(0, 'on time only'), (5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='facebook_target_search',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 9, 45, 22, 104904, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facebook_target_search',
            name='periodic_interval',
            field=models.IntegerField(choices=[(0, 'on time only'), (5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='instagram_target_person',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 9, 45, 22, 107305, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instagram_target_person',
            name='periodic_interval',
            field=models.IntegerField(choices=[(0, 'on time only'), (5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='instagram_target_search',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 9, 45, 22, 107754, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instagram_target_search',
            name='periodic_interval',
            field=models.IntegerField(choices=[(0, 'on time only'), (5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='news_site_target',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 9, 45, 22, 106799, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news_site_target',
            name='periodic_interval',
            field=models.IntegerField(choices=[(0, 'on time only'), (5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='twitter_target_hashtag',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 9, 45, 22, 105878, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='twitter_target_hashtag',
            name='periodic_interval',
            field=models.IntegerField(choices=[(0, 'on time only'), (5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='twitter_target_person',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 9, 45, 22, 105422, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='twitter_target_person',
            name='periodic_interval',
            field=models.IntegerField(choices=[(0, 'on time only'), (5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='twitter_target_search',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 9, 45, 22, 106348, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='twitter_target_search',
            name='periodic_interval',
            field=models.IntegerField(choices=[(0, 'on time only'), (5, 'once per 5 minutes '), (10, 'once per 10 minutes '), (15, 'once per 15 minutes '), (30, 'once per 30 minutes '), (40, 'once per 40 minutes '), (60, 'once per 60 minutes '), (90, 'once per 90 minutes '), (120, 'once per 120 minutes '), (180, 'once per 180 minutes '), (360, 'once per 360 minutes '), (720, 'once per 720 minutes ')], max_length=50),
        ),
    ]
