# Generated by Django 2.2.7 on 2020-01-14 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Public_Data_Acquisition_Unit', '0012_auto_20200101_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook_target_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 12, 4, 54, 854034, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facebook_target_hashtag',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 12, 4, 54, 854445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facebook_target_page',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 12, 4, 54, 853593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facebook_target_page',
            name='expired_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='facebook_target_person',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 12, 4, 54, 853030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='facebook_target_search',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 12, 4, 54, 854846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instagram_target_person',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 12, 4, 54, 857188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instagram_target_search',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 12, 4, 54, 857695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='linkedin_target_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 12, 4, 54, 858605, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='linkedin_target_person',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 12, 4, 54, 858148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news_site_target',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 12, 4, 54, 856769, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='twitter_target_hashtag',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 12, 4, 54, 855920, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='twitter_target_person',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 12, 4, 54, 855332, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='twitter_target_search',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 12, 4, 54, 856361, tzinfo=utc)),
        ),
    ]
