# Generated by Django 2.2.7 on 2020-02-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Public_Data_Acquisition_Unit', '0014_auto_20200114_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebook_target_hashtag',
            name='global_target_reff',
        ),
        migrations.RemoveField(
            model_name='facebook_target_page',
            name='global_target_reff',
        ),
        migrations.RemoveField(
            model_name='facebook_target_person',
            name='global_target_reff',
        ),
        migrations.RemoveField(
            model_name='facebook_target_search',
            name='global_target_reff',
        ),
        migrations.RemoveField(
            model_name='global_target_record',
            name='social_site_reff',
        ),
        migrations.RemoveField(
            model_name='instagram_target_person',
            name='global_target_reff',
        ),
        migrations.RemoveField(
            model_name='instagram_target_search',
            name='global_target_reff',
        ),
        migrations.RemoveField(
            model_name='linkedin_target_company',
            name='global_target_reff',
        ),
        migrations.RemoveField(
            model_name='linkedin_target_person',
            name='global_target_reff',
        ),
        migrations.RemoveField(
            model_name='news_site_target',
            name='global_target_reff',
        ),
        migrations.RemoveField(
            model_name='twitter_target_hashtag',
            name='global_target_reff',
        ),
        migrations.RemoveField(
            model_name='twitter_target_person',
            name='global_target_reff',
        ),
        migrations.RemoveField(
            model_name='twitter_target_search',
            name='global_target_reff',
        ),
        migrations.DeleteModel(
            name='Facebook_Target_Group',
        ),
        migrations.DeleteModel(
            name='Facebook_Target_Hashtag',
        ),
        migrations.DeleteModel(
            name='Facebook_Target_Page',
        ),
        migrations.DeleteModel(
            name='Facebook_Target_Person',
        ),
        migrations.DeleteModel(
            name='Facebook_Target_Search',
        ),
        migrations.DeleteModel(
            name='Global_Target_Record',
        ),
        migrations.DeleteModel(
            name='Instagram_Target_Person',
        ),
        migrations.DeleteModel(
            name='Instagram_Target_Search',
        ),
        migrations.DeleteModel(
            name='Linkedin_Target_Company',
        ),
        migrations.DeleteModel(
            name='Linkedin_Target_Person',
        ),
        migrations.DeleteModel(
            name='News_Site_Target',
        ),
        migrations.DeleteModel(
            name='Twitter_Target_Hashtag',
        ),
        migrations.DeleteModel(
            name='Twitter_Target_Person',
        ),
        migrations.DeleteModel(
            name='Twitter_Target_Search',
        ),
    ]
