# Generated by Django 2.2.7 on 2019-12-05 11:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supported_Socail_Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('website_status', models.BooleanField(default=True)),
                ('health_status', models.CharField(choices=[('good', 'Health is good'), ('ok', 'Health is ok'), ('bad', 'Health is bad')], max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 11, 31, 51, 262299, tzinfo=utc))),
                ('created_by', models.ForeignKey(default='this user is deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
