# Generated by Django 2.2.7 on 2019-12-10 07:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT_System_Core', '0002_auto_20191205_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword_Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('impact', models.CharField(choices=[('+ve', 'Positive Impact'), ('-ve', 'Negative Impact')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='supported_socail_sites',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 7, 22, 58, 264570, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_list', models.CharField(max_length=500)),
                ('keyword_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OSINT_System_Core.Keyword_Groups')),
            ],
        ),
    ]
