# Generated by Django 2.2.7 on 2019-12-10 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT_System_Core', '0003_auto_20191210_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='supported_socail_sites',
            name='website_type',
            field=models.CharField(choices=[('ss', 'Social Site'), ('ns', 'News Site'), ('bs', 'Blog Site')], default='bs', max_length=20),
        ),
        migrations.AlterField(
            model_name='supported_socail_sites',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 7, 44, 0, 363483, tzinfo=utc)),
        ),
    ]
